[package]
name = "systest"
version = "0.1.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
publish = false

build = "build.rs"

[dependencies]
audio-toolbox-sys = { path = "../audio-toolbox-sys" }

[build-dependencies]
ctest = "0.1.7"